const ItemsBought = {
    SET_CURRENT_BUYINGS: 'SET_CURRENT_BUYINGS',
    ADD_NEW_BOUGHT: 'ADD_NEW_BOUGHT',
    GET_BOUGHT: 'GET_BOUGHT_ITEMS',
    FINISHED_FETCH_BOUGHT: 'FINISHED_FETCH_BOUGHT'
};
  
  export default ItemsBought;
  